version: "3.8" 
services:
  db:
    container_name: king-db
    image: postgres:12 
    volumes: 
      - type: volume
        source: k1ngSocialMedia
        target: /var/lib/postgresql/data
    ports:
      - "2727:5432"
    environment: 
      POSTGRES_USER: king
      POSTGRES_DB: kingSocialMedia
      POSTGRES_PASSWORD: king
  main:
    container_name: go-app
    build:
      context: .
      dockerfile: Dockerfile
    command: ./app
    ports:
      - "8010:8010"
    depends_on:
      - db
volumes:
  k1ngSocialMedia:
    driver: local

# docker exec -it king-db /bin/bash
# psql -U king -d kingSocialMedia